// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPersonne.Data;

namespace Vaccinator.Migrations
{
    [DbContext(typeof(MvcPersonneContext))]
    [Migration("20210221124714_myMigration")]
    partial class myMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("MvcInjection.Models.Injection", b =>
                {
                    b.Property<int>("idInjection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("PersonneidPersonne")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_rappel")
                        .HasColumnType("datetime2");

                    b.HasKey("idInjection");

                    b.HasIndex("PersonneidPersonne");

                    b.ToTable("Injection");
                });

            modelBuilder.Entity("MvcPersonne.Models.Personne", b =>
                {
                    b.Property<int>("idPersonne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("date_naissance")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isResident")
                        .HasColumnType("bit");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sexe")
                        .HasColumnType("bit");

                    b.HasKey("idPersonne");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("MvcInjection.Models.Injection", b =>
                {
                    b.HasOne("MvcPersonne.Models.Personne", null)
                        .WithMany("Injections")
                        .HasForeignKey("PersonneidPersonne");
                });

            modelBuilder.Entity("MvcPersonne.Models.Personne", b =>
                {
                    b.Navigation("Injections");
                });
#pragma warning restore 612, 618
        }
    }
}
